### ISSUE TITLE
Mypy checks crush in attempt to connect database

### ISSUE THREAD

**Issue by Bizilizi** [typeddjango/django-stubs#1060]
# Bug report

## What's wrong
Mypy call crushes in attempt to connect a database. To be specific, we run following code on our Django project:
```
mypy src
```

And in response we receive the following error:
```
django.db.utils.OperationalError: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?
```

Seems like django is trying to run migration related modules during type checking and since we develop everything locally we end up having connection exception. Here is a full traceback:
```
Error constructing plugin instance of NewSemanalDjangoPlugin

Traceback (most recent call last):
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/django/db/backends/base/base.py", line 244, in ensure_connection
    self.connect()
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/django/db/backends/base/base.py", line 225, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 203, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/mypy/__main__.py", line 12, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 96, in main
  File "mypy/main.py", line 173, in run_build
  File "mypy/build.py", line 180, in build
  File "mypy/build.py", line 231, in _build
  File "mypy/build.py", line 478, in load_plugins
  File "mypy/build.py", line 456, in load_plugins_from_config
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/mypy_django_plugin/main.py", line 71, in __init__
    self.django_context = DjangoContext(self.plugin_config.django_settings_module)
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/mypy_django_plugin/django/context.py", line 97, in __init__
    apps, settings = initialize_django(self.django_settings_module)
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/mypy_django_plugin/django/context.py", line 81, in initialize_django
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/django_prometheus/apps.py", line 24, in ready
    ExportMigrations()
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/django_prometheus/migrations.py", line 52, in ExportMigrations
    executor = MigrationExecutor(connections[alias])
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/django/db/migrations/loader.py", line 235, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
    if self.has_table():
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 57, in has_table
    with self.connection.cursor() as cursor:
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/django_query_profiler/django/db/backends/database_wrapper_mixin.py", line 18, in cursor
    cursor_wrapper = super().cursor()
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/django/db/backends/base/base.py", line 284, in cursor
    return self._cursor()
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/django/db/backends/base/base.py", line 260, in _cursor
    self.ensure_connection()
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/django/db/backends/base/base.py", line 244, in ensure_connection
    self.connect()
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/django/db/backends/base/base.py", line 244, in ensure_connection
    self.connect()
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/django/db/backends/base/base.py", line 225, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 203, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/Users/ewriji/.cache/pre-commit/repo71cm5oza/py_env-python3.9/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?
``` 

## System information
As a framework we use [django-ninja ](https://django-ninja.rest-framework.com/), all the checks are performed by pre-commit.

- OS:
- `python` version: 3.9
- `django` version: 4.0.6
- `mypy` version: v0.942
- `django-stubs` version: 1.12.0
- `django-stubs-ext` version: 0.5.0

All the configuration w.r.t mypy we keep in `setup.cfg`, here are related parts:
```
[mypy]
plugins = mypy_django_plugin.main, pydantic.mypy
python_version = 3.9

[mypy.plugins.django-stubs]
django_settings_module = "src.configuration.settings"

[mypy-*.migrations.*]
ignore_errors = True
```

**Comment by flaeppe** [comment]
Seems like one of your apps is what's causing the error here. From reading the traceback it looks like it triggers some migration stuff that wants some database connection.

The `django-stubs` plugin needs to run `django.setup()` to work, which in turn will require the database connection due to that app.

I would suggest looking over how you can adjust the app requiring a database connection on apps ready. As the django stubs plugin cannot work without running `django.setup()`, and that won't change any time soon
