### ISSUE TITLE
Plugin can't find Django module file

### ISSUE THREAD

**Issue by SHxKM** [typeddjango/django-stubs#133]
Below is my `mypy.ini` which is at the root of my project:

```ini
[mypy]

warn_unused_ignores = True
strict_optional = True
check_untyped_defs = True
follow_imports = silent
ignore_missing_imports = True

plugins = 
    mypy_django_plugin.main

[mypy.plugins.django-stubs]

django_settings_module = "my_app.settings.dev"
```

When I run `mypy some_app/some_file.py` I get an error:

> ModuleNotFoundError: No module named 'my_app'

I'm using `pip` (not `pipevn`) and running inside a `virtualenv`

**Comment by sobolevn** [comment]
Have you tried `PYTHONPATH=${PYTHONPATH}:${PWD}`?
We have this in the docs: 
<img width="894" alt="Снимок экрана 2019-08-14 в 11 31 54" src="https://user-images.githubusercontent.com/4660275/63006395-227d2500-be87-11e9-9ba9-3a30538dcaca.png">

**Comment by SHxKM** [comment]
@sobolevn - yes I have. It doesn’t have any effect.

**Comment by SHxKM** [comment]
Adding some more info to this: As soon as I remove these three lines:

```
plugins = 
    mypy_django_plugin.main

[mypy.plugins.django-stubs]

django_settings_module = "my_app.settings.dev"
```

`mypy` works again (at least in VSCode editor highlights and without the django functionality of course). I obviously cannot run `mypy some_file.py/some_module_with_django_code` because that's what's the plugin is supposed to let me do but what I'm saying is that something with the way the settings module is read is breaking the whole plugin and `mypy` itself. Here's the traceback:

```
Traceback (most recent call last):
  File "/Users/username/.virtualenvs/bap_dev/bin/mypy", line 10, in <module>
    sys.exit(console_entry())
  File "/Users/username/.virtualenvs/bap_dev/lib/python3.6/site-packages/mypy/__main__.py", line 8, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 83, in main
  File "mypy/build.py", line 164, in build
  File "mypy/build.py", line 202, in _build
  File "mypy/build.py", line 406, in load_plugins
  File "/Users/username/.virtualenvs/bap_dev/lib/python3.6/site-packages/mypy/interpreted_plugin.py", line 28, in __new__
    plugin.__init__(*args, **kwargs)
  File "/Users/username/.virtualenvs/bap_dev/lib/python3.6/site-packages/mypy_django_plugin/main.py", line 76, in __init__
    self.django_context = DjangoContext(django_settings_module)
  File "/Users/username/.virtualenvs/bap_dev/lib/python3.6/site-packages/mypy_django_plugin/django/context.py", line 168, in __init__
    apps, settings = initialize_django(self.django_settings_module)
  File "/Users/username/.virtualenvs/bap_dev/lib/python3.6/site-packages/mypy_django_plugin/django/context.py", line 61, in initialize_django
    settings._setup()
  File "/Users/username/.virtualenvs/bap_dev/lib/python3.6/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/username/.virtualenvs/bap_dev/lib/python3.6/site-packages/django/conf/__init__.py", line 107, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Users/username/.pyenv/versions/3.6.1/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  ...
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'my_app'
```

**Comment by SHxKM** [comment]
I guess I wasn't setting `PYTHONPATH` correctly after all because `PYTHONPATH=${PYTHONPATH}:${pwd} mypy ...` does work.

**Comment by sobolevn** [comment]
@SHxKM glad that it worked! I guess that I can improve the docs to show that this command should be prepended to the `mypy` call.

I will reopen the issue to fix it.

Thanks for bringing this up!

**Comment by SHxKM** [comment]
> Thanks for bringing this up!

Thank **you** for the hard work and welcoming attitude.

> I guess that I can improve the docs to show that this command should be prepended to the mypy call.

Yep. It is quite unclear as it stands now because usually this kind of stuff is declared in a file or in the Terminal prompt as a separate command. 

Now that it's working there's another issue which is that it's ignoring the other configs, like:

```ini
warn_unused_ignores = True
strict_optional = True
check_untyped_defs = True
follow_imports = silent
ignore_missing_imports = True
show_column_numbers = True
```

For example, I had to do this to get `silent-imports`:

```
PYTHONPATH=${PYTHONPATH}:${PWD} mypy core/selectors.py --follow-imports=silent
```

But I guess that's a separate issue (or just something entirely different that I'm also misunderstanding 😕) 

**EDIT** in case someone is facing the same problem: I had the settings under the wrong sections in the `ini` file. So change this:


```ini
[mypy]
plugins = mypy_django_plugin.main
[mypy.plugins.django-stubs]
django_settings_module = my_app.settings.dev

warn_unused_ignores = True
strict_optional = True
check_untyped_defs = True
follow_imports = silent
ignore_missing_imports = True
show_column_numbers = True
```

to this:

```ini
[mypy]
plugins = mypy_django_plugin.main

warn_unused_ignores = True
strict_optional = True
check_untyped_defs = True
follow_imports = silent
ignore_missing_imports = True
show_column_numbers = True

[mypy.plugins.django-stubs]
django_settings_module = my_app.settings.dev
```

**Comment by skrat** [comment]
This may sound convoluted by I'm running into this issue in Emacs / flycheck / python-mypy checker. I just hope there's an emacs user somewhere near this issue. I did edit `.env` and I believe my conf. is all right, at least per the docs. Following makes me believe that everything is running in the right virtual env. 

```
Traceback (most recent call last):
  File "/home/skrat/.cache/pypoetry/virtualenvs/gates-ntz_JxQx-py3.9/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/skrat/.cache/pypoetry/virtualenvs/gates-ntz_JxQx-py3.9/lib/python3.9/site-packages/mypy/__main__.py", line 8, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/home/skrat/.cache/pypoetry/virtualenvs/gates-ntz_JxQx-py3.9/lib/python3.9/site-packages/mypy/main.py", line 90, in main
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/home/skrat/.cache/pypoetry/virtualenvs/gates-ntz_JxQx-py3.9/lib/python3.9/site-packages/mypy/build.py", line 180, in build
    result = _build(
  File "/home/skrat/.cache/pypoetry/virtualenvs/gates-ntz_JxQx-py3.9/lib/python3.9/site-packages/mypy/build.py", line 229, in _build
    plugin, snapshot = load_plugins(options, errors, stdout, extra_plugins)
  File "/home/skrat/.cache/pypoetry/virtualenvs/gates-ntz_JxQx-py3.9/lib/python3.9/site-packages/mypy/build.py", line 472, in load_plugins
    custom_plugins, snapshot = load_plugins_from_config(options, errors, stdout)
  File "/home/skrat/.cache/pypoetry/virtualenvs/gates-ntz_JxQx-py3.9/lib/python3.9/site-packages/mypy/build.py", line 450, in load_plugins_from_config
    custom_plugins.append(plugin_type(options))
  File "/home/skrat/.cache/pypoetry/virtualenvs/gates-ntz_JxQx-py3.9/lib/python3.9/site-packages/mypy_django_plugin/main.py", line 100, in __init__
    self.django_context = DjangoContext(django_settings_module)
  File "/home/skrat/.cache/pypoetry/virtualenvs/gates-ntz_JxQx-py3.9/lib/python3.9/site-packages/mypy_django_plugin/django/context.py", line 88, in __init__
    apps, settings = initialize_django(self.django_settings_module)
  File "/home/skrat/.cache/pypoetry/virtualenvs/gates-ntz_JxQx-py3.9/lib/python3.9/site-packages/mypy_django_plugin/django/context.py", line 70, in initialize_django
    settings._setup()
  File "/home/skrat/.cache/pypoetry/virtualenvs/gates-ntz_JxQx-py3.9/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/skrat/.cache/pypoetry/virtualenvs/gates-ntz_JxQx-py3.9/lib/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'gates'

Try installing a more recent version of python-mypy, and please open a bug report if the issue persists in the latest release.  Thanks!
```

mypy.ini

```
[mypy]
plugins =
    mypy_django_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = "gates.settings"
```

.env

```
#!/usr/bin/env bash
set -euo pipefail

PYTHONPATH=${PYTHONPATH}:${PWD}
DJANGO_SETTINGS_MODULE=gates.settings
```

**Comment by PyB1l** [comment]
@skrat I am trying to resolve the same issue as well with (doom) emacs and flycheck - mypy. I think it's a path related issue as flycheck seems to run mypy from different dir and cannot setup django. I am trying to resolve it with dir-locals.el file but still no luck

**Comment by chocoelho** [comment]
@PyB1l wouldn't something like https://github.com/flycheck/flycheck/issues/1829 help?

**Comment by flaeppe** [comment]
I think we should close this. There are multiple ways of how an environment could be configured to have Django and/or mypy running, I don't think we should stretch to say how.

Anyways, it has also been quiet for some time here and I get a feeling that any further discussion/questions could fit better under https://github.com/typeddjango/django-stubs/discussions
