### ISSUE TITLE
`get_user_model_hook` raises `LookupError` without `auth` app

### ISSUE THREAD

**Issue by meshy** [typeddjango/django-stubs#1380]
# Bug report

## What's wrong

Djangn-stubs causes mypy to crashe with `LookupError` when:
- `django.contrib.auth` is not in `INSTALLED_APPS`,
- any imported code references `get_user_model()`.

This happened to me because I'm importing `SettingsWrapper` from `pytest_django.fixtures`. Mypy then wants a type for `get_user_model` because [`pytest_django`'s `django_user_model` fixture imports and returns `get_user_model()`](https://github.com/pytest-dev/pytest-django/blob/d9b93568fb27b45340fa525c33112383ada66a3d/pytest_django/fixtures.py#L390-L395) in that module.

When `get_user_model_hook` is called, but the `auth` app isn't installed, Django raises a `LookupError`. I must admit, I have no idea what it _should_ return.

This is similar to https://github.com/typeddjango/django-stubs/issues/318.

Traceback:
```
Traceback (most recent call last):
  File "mypy/checkexpr.py", line 4813, in accept
  File "mypy/checkexpr.py", line 425, in visit_call_expr
  File "mypy/checkexpr.py", line 545, in visit_call_expr_inner
  File "mypy/checkexpr.py", line 1197, in check_call_expr_with_callee_type
  File "mypy/checkexpr.py", line 1280, in check_call
  File "mypy/checkexpr.py", line 1490, in check_callable_call
  File "mypy/checkexpr.py", line 1020, in apply_function_plugin
  File "/.../python3.10/site-packages/mypy_django_plugin/transformers/settings.py", line 13, in get_user_model_hook
    model_cls = django_context.apps_registry.get_model(auth_user_model)
  File "/.../python3.10/site-packages/django/apps/registry.py", line 206, in get_model
    app_config = self.get_app_config(app_label)
  File "/.../python3.10/site-packages/django/apps/registry.py", line 163, in get_app_config
    raise LookupError(message)
LookupError: No installed app with label 'auth'.

/.../python3.10/site-packages/pytest_django/fixtures.py:397: : note: use --pdb to drop into pdb
```

## How it should work

`get_user_model_hook` should not raise an error when there is no `auth` app.

## System information

- OS: Ubuntu 22.04.2 LTS
- `python` version: `3.10.6`
- `django` version: `3.1`
- `mypy` version: `1.0.1`
- `django-stubs` version: `1.15.0` 
- `django-stubs-ext` version: `0.7.0`

**Comment by BranislavBajuzik** [comment]
I had this exact problem. The Mypy code that throws this uses your `settings.AUTH_USER_MODEL`. My problem was that I pointed to empty (the `__init__.py` :sweat_smile:) settings so the default value of `auth.User` was used instead of what I put in there.
