### ISSUE TITLE
ValueError: Related model 'accounts.user' cannot be resolved

### ISSUE THREAD

**Issue by AbdusalomovIbroxim** [typeddjango/django-stubs#1762]
# Bug report
For some reason I changed the name of the class then I had to return it, but this was an error when migrating

# What's wrong

> [!WARNING]
```(venv) ibroxim@ibroxim-IdeaPad-3-15IIL05:~/PycharmProjects/Technoprom (copy)$ python manage.py migrate
Operations to perform:
  Apply all migrations: accounts, admin, auth, contenttypes, films, sessions
Running migrations:
  Applying accounts.0023_userprofile_companyprofile_delete_user_and_more...Traceback (most recent call last):
  File "/home/ibroxim/PycharmProjects/Technoprom (copy)/manage.py", line 22, in <module>
    main()
  File "/home/ibroxim/PycharmProjects/Technoprom (copy)/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ibroxim/PycharmProjects/Technoprom/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/ibroxim/PycharmProjects/Technoprom/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ibroxim/PycharmProjects/Technoprom/venv/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ibroxim/PycharmProjects/Technoprom/venv/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/ibroxim/PycharmProjects/Technoprom/venv/lib/python3.10/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/home/ibroxim/PycharmProjects/Technoprom/venv/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
  File "/home/ibroxim/PycharmProjects/Technoprom/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/home/ibroxim/PycharmProjects/Technoprom/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "/home/ibroxim/PycharmProjects/Technoprom/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/ibroxim/PycharmProjects/Technoprom/venv/lib/python3.10/site-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/home/ibroxim/PycharmProjects/Technoprom/venv/lib/python3.10/site-packages/django/db/migrations/operations/fields.py", line 235, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/home/ibroxim/PycharmProjects/Technoprom/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/schema.py", line 173, in alter_field
    super().alter_field(model, old_field, new_field, strict=strict)
  File "/home/ibroxim/PycharmProjects/Technoprom/venv/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 788, in alter_field
    old_db_params = old_field.db_parameters(connection=self.connection)
  File "/home/ibroxim/PycharmProjects/Technoprom/venv/lib/python3.10/site-packages/django/db/models/fields/related.py", line 1166, in db_parameters
    target_db_parameters = self.target_field.db_parameters(connection)
  File "/home/ibroxim/PycharmProjects/Technoprom/venv/lib/python3.10/site-packages/django/db/models/fields/related.py", line 1059, in target_field
    return self.foreign_related_fields[0]
  File "/home/ibroxim/PycharmProjects/Technoprom/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ibroxim/PycharmProjects/Technoprom/venv/lib/python3.10/site-packages/django/db/models/fields/related.py", line 746, in foreign_related_fields
    rhs_field for lhs_field, rhs_field in self.related_fields if rhs_field
  File "/home/ibroxim/PycharmProjects/Technoprom/venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ibroxim/PycharmProjects/Technoprom/venv/lib/python3.10/site-packages/django/db/models/fields/related.py", line 733, in related_fields
    return self.resolve_related_fields()
  File "/home/ibroxim/PycharmProjects/Technoprom/venv/lib/python3.10/site-packages/django/db/models/fields/related.py", line 1086, in resolve_related_fields
    related_fields = super().resolve_related_fields()
  File "/home/ibroxim/PycharmProjects/Technoprom/venv/lib/python3.10/site-packages/django/db/models/fields/related.py", line 711, in resolve_related_fields
    raise ValueError(
ValueError: Related model 'accounts.user' cannot be resolved
```

# User model

```from django.contrib.auth.models import AbstractUser
    from django.db.models import Model, CharField, ImageField, ....
    from films.models import Categories, SubCategories, Tag, Country
    from django.db.models import Avg


    class User(AbstractUser):
        telephone = CharField(max_length=50, null=True, blank=True)
        email = EmailField(unique=True)
        trust = BooleanField(default=False)
        profile_photo = ImageField(upload_to='profile_photos/', default='static/default-logo.svg')
    
        company_name = CharField(max_length=100, blank=True, null=True)
        category = ForeignKey(Categories, SET_NULL, blank=True, null=True, related_name='user_category')
        sub_category = ForeignKey(SubCategories, SET_NULL, blank=True, null=True, related_name='user_sub_category')
        tags = ManyToManyField(Tag, blank=True)
    
        telegram = CharField(max_length=100, blank=True, null=True)
        whatsapp = CharField(max_length=100, blank=True, null=True)
        website = CharField(max_length=500, blank=True, null=True)
        url_maps = CharField(max_length=500, blank=True, null=True)
    
        banner = ImageField(upload_to='company_banners/', blank=True, null=True)
        logo = ImageField(upload_to='company_logos/', blank=True, null=True)
    
        description = CharField(max_length=1000, blank=True, null=True)
        country = ForeignKey(Country, SET_NULL, blank=True, null=True)
        is_business_account = BooleanField(default=False, null=True)
    
        def __str__(self):
            return self.username
    
        class Meta(AbstractUser.Meta):
            swappable = 'AUTH_USER_MODEL'
    
        def calculate_average_rating(self):
            return UserRating.objects.filter(rated_user=self).aggregate(Avg('rating'))['rating__avg'] or 0
    
    
    class Notification(Model):
        user = ForeignKey(User, on_delete=CASCADE)
        message = TextField()
        created_at = DateTimeField(auto_now_add=True)
        is_read = BooleanField(default=False)
    
    
    class UserRating(Model):
        rater = ForeignKey(User, related_name='ratings_given', on_delete=CASCADE)
        rated_user = ForeignKey(User, related_name='ratings_received', on_delete=CASCADE)
        rating = PositiveIntegerField()
    
        def __str__(self):
            return f"Rating from {self.rater} to {self.rated_user}: {self.rating}"
    
        class Meta:
            unique_together = (('rater', 'rated_user'),)

```

# System information

- OS: Linux Ubuntu
- python version: 3.10
- django version: 4.2.2

**Comment by flaeppe** [comment]
I'm getting a feeling this has nothing to do with `django-stubs`? Especially since the traceback seems to display execution of e.g. `python manage.py migrate`

I'm totally fine with reopening this with a different description, but I'm going to close this off for now
