### ISSUE TITLE
Abstract models from library cause a crash

### ISSUE THREAD

**Issue by rik** [typeddjango/django-stubs#185]
I'm using https://github.com/django-oscar/django-oscar which provides abstract models to subclass in your app. Because Oscar does not provide type hints, I'm adding a local stub file to help `django-stubs` find this model (instead of typing it as `Any`). Doing so causes a crash (see traceback below) in `AddRelatedModelsId` on an abstract model that has a foreign key on `'self'` ([`AbstractProduct.parent`](https://github.com/django-oscar/django-oscar/blob/186f60df05cf852494fcb0c3bc76813201701bae/src/oscar/apps/catalogue/abstract_models.py#L278)).

In my debugging, I'm wondering if the rule in [`DjangoFieldsContext.get_related_model_cls`](https://github.com/typeddjango/django-stubs/blob/7407b9315109b33ae8c6066c4be7ac1920919f0e/mypy_django_plugin/django/context.py#L144) is too simple. Maybe it should find concrete models?

There's also a great chance than I'm using `django-stubs` badly in this case. Should I type this differently?

## Stub
```pyi
from django.db import models

class AbstractProduct(models.Model): ...
```
## Traceback
```pytb
Traceback (most recent call last):
  File "mypy/newsemanal/semanal.py", line 4550, in accept
  File "mypy/nodes.py", line 921, in accept__Node_glue
  File "mypy/nodes.py", line 922, in accept
  File "mypy/newsemanal/semanal.py", line 989, in visit_class_def__StatementVisitor_glue
  File "mypy/newsemanal/semanal.py", line 992, in visit_class_def
  File "mypy/newsemanal/semanal.py", line 1063, in analyze_class
  File "mypy/newsemanal/semanal.py", line 1072, in analyze_class_body_common
  File "mypy/newsemanal/semanal.py", line 1131, in apply_class_plugin_hooks
  File "/venv/site-packages/mypy_django_plugin/main.py", line 33, in transform_model_class
    process_model_class(ctx, django_context)
  File "/venv/site-packages/mypy_django_plugin/transformers/models.py", line 228, in process_model_class
    initializer_cls(ctx, django_context).run()
  File "/venv/site-packages/mypy_django_plugin/transformers/models.py", line 60, in run
    self.run_with_model_cls(model_cls)
  File "/venv/site-packages/mypy_django_plugin/transformers/models.py", line 104, in run_with_model_cls
    rel_primary_key_field = self.django_context.get_primary_key_field(related_model_cls)
  File "/venv/site-packages/mypy_django_plugin/django/context.py", line 231, in get_primary_key_field
    raise ValueError('No primary key defined')
```

**Comment by mkurnikov** [comment]
> Doing so causes a crash (see traceback below) in AddRelatedModelsId on an abstract model that has a foreign key on 'self' (AbstractProduct.parent).

Could you provide an example?

**Comment by rik** [comment]
`AbstractProduct.parent` has a link to django-oscar's code (https://github.com/django-oscar/django-oscar/blob/186f60df05cf852494fcb0c3bc76813201701bae/src/oscar/apps/catalogue/abstract_models.py#L278). Is that the example you're asking for?

**Comment by TyVik** [comment]
One more example https://circleci.com/gh/TyVik/geopuzzle/3423. Even with `# typing: ignore`.

**Comment by strokirk** [comment]
I'm seeing this as well. Here is a test that reproduces the issue – hope it helps!

```
# test-data/typecheck/fields/test_related.yml
-   case: foreign_key_with_abstract_self
    main: |
        from myapp.models import User
        reveal_type(User().parent)  # N: Revealed type is 'myapp.models.User*'
    installed_apps:
        - myapp
    files:
        -   path: myapp/__init__.py
        -   path: myapp/models.py
            content: |
                from django.db import models
                class AbstractUser(models.Model):
                    parent = models.ForeignKey('self', on_delete=models.CASCADE)
                    class Meta:
                        abstract = True
                class User(AbstractUser):
                    pass
```
