### ISSUE TITLE
Error with latest mypy release (0.750)

### ISSUE THREAD

**Issue by anlambert** [typeddjango/django-stubs#236]
Due to that [recent change](https://github.com/python/mypy/commit/e97377c454a1d5c019e9c56871d5f229db6b47b2#diff-abd352ca9f518956b2d76e1cfc9ad35b) in `mypy` source code, the following error is reported when using `django-stubs`
```
mypy run-test: commands[0] | mypy swh
Traceback (most recent call last):
  File "/home/antoine/swh/swh-environment/swh-web/.tox/mypy/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/antoine/swh/swh-environment/swh-web/.tox/mypy/lib/python3.7/site-packages/mypy/__main__.py", line 8, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 89, in main
  File "mypy/build.py", line 166, in build
  File "mypy/build.py", line 235, in _build
  File "mypy/build.py", line 2567, in dispatch
  File "mypy/build.py", line 2725, in load_graph
  File "mypy/build.py", line 1826, in __init__
  File "mypy/build.py", line 2101, in compute_dependencies
  File "mypy/plugin.py", line 785, in get_additional_deps
  File "mypy/plugin.py", line 711, in get_additional_deps
  File "/home/antoine/swh/swh-environment/swh-web/.tox/mypy/lib/python3.7/site-packages/mypy_django_plugin/main.py", line 124, in get_additional_deps
    if file.fullname() == 'django.conf' and self.django_context.django_settings_module:
TypeError: 'str' object is not callable
ERROR: InvocationError for command /home/antoine/swh/swh-environment/swh-web/.tox/mypy/bin/mypy swh (exited with code 1)
```

**Comment by mkurnikov** [comment]
Fixed via https://github.com/typeddjango/django-stubs/pull/238
