### ISSUE TITLE
IndexError in `is_any_parametrized_manager`

### ISSUE THREAD

**Issue by dfarley1** [typeddjango/django-stubs#308]
## What's wrong

I'm adding mypy and djang-stubs to our repo but I'm running into the following error when enabling the django-stubs plugin. This is happening even with my own INSTALLED_APPS disabled in the settings module:
```
INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
}
```

```
/depot/vendor/Django/django/contrib/contenttypes/models.py:133: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.760
/depot/vendor/Django/django/contrib/sessions/base_session.py:26: : note: use --pdb to drop into pdb
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib64/python3.6/site-packages/mypy/__main__.py", line 12, in <module>
    main(None, sys.stdout, sys.stderr)
  File "/usr/lib64/python3.6/site-packages/mypy/main.py", line 89, in main
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/usr/lib64/python3.6/site-packages/mypy/build.py", line 167, in build
    sources, options, alt_lib_path, flush_errors, fscache, stdout, stderr, extra_plugins
  File "/usr/lib64/python3.6/site-packages/mypy/build.py", line 235, in _build
    graph = dispatch(sources, manager, stdout)
  File "/usr/lib64/python3.6/site-packages/mypy/build.py", line 2611, in dispatch
    process_graph(graph, manager)
  File "/usr/lib64/python3.6/site-packages/mypy/build.py", line 2918, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/usr/lib64/python3.6/site-packages/mypy/build.py", line 3011, in process_stale_scc
    mypy.semanal_main.semantic_analysis_for_scc(graph, scc, manager.errors)
  File "/usr/lib64/python3.6/site-packages/mypy/semanal_main.py", line 77, in semantic_analysis_for_scc
    process_top_levels(graph, scc, patches)
  File "/usr/lib64/python3.6/site-packages/mypy/semanal_main.py", line 202, in process_top_levels
    patches)
  File "/usr/lib64/python3.6/site-packages/mypy/semanal_main.py", line 330, in semantic_analyze_target
    active_type=active_type)
  File "/usr/lib64/python3.6/site-packages/mypy/semanal.py", line 378, in refresh_partial
    self.refresh_top_level(node)
  File "/usr/lib64/python3.6/site-packages/mypy/semanal.py", line 389, in refresh_top_level
    self.accept(d)
  File "/usr/lib64/python3.6/site-packages/mypy/semanal.py", line 4665, in accept
    node.accept(self)
  File "/usr/lib64/python3.6/site-packages/mypy/nodes.py", line 939, in accept
    return visitor.visit_class_def(self)
  File "/usr/lib64/python3.6/site-packages/mypy/semanal.py", line 1029, in visit_class_def
    self.analyze_class(defn)
  File "/usr/lib64/python3.6/site-packages/mypy/semanal.py", line 1106, in analyze_class
    self.analyze_class_body_common(defn)
  File "/usr/lib64/python3.6/site-packages/mypy/semanal.py", line 1115, in analyze_class_body_common
    self.apply_class_plugin_hooks(defn)
  File "/usr/lib64/python3.6/site-packages/mypy/semanal.py", line 1175, in apply_class_plugin_hooks
    hook(ClassDefContext(defn, base_expr, self))
  File "/usr/lib64/python3.6/site-packages/mypy_django_plugin/main.py", line 37, in transform_model_class
    process_model_class(ctx, django_context)
  File "/usr/lib64/python3.6/site-packages/mypy_django_plugin/transformers/models.py", line 357, in process_model_class
    initializer_cls(ctx, django_context).run()
  File "/usr/lib64/python3.6/site-packages/mypy_django_plugin/transformers/models.py", line 71, in run
    self.run_with_model_cls(model_cls)
  File "/usr/lib64/python3.6/site-packages/mypy_django_plugin/transformers/models.py", line 225, in run_with_model_cls
    if not self.has_any_parametrized_manager_as_base(manager_info):
  File "/usr/lib64/python3.6/site-packages/mypy_django_plugin/transformers/models.py", line 148, in has_any_parametrized_manager_as_base
    if self.is_any_parametrized_manager(base):
  File "/usr/lib64/python3.6/site-packages/mypy_django_plugin/transformers/models.py", line 153, in is_any_parametrized_manager
    return typ.type.fullname in fullnames.MANAGER_CLASSES and isinstance(typ.args[0], AnyType)
IndexError: list index out of range
```

## System information

- OS: Gentoo
- `python` version: 3.6
- `django` version: 2.2.9
- `mypy` version: 0.760
- `django-stubs` version: 1.4.0

**Comment by dfarley1** [comment]
Dropping into pdb it looks like `isinstance(typ.args[0], AnyType)` fails because `typ.args` is empty for the Django base Manager,
```
(Pdb) p typ
django.db.models.manager.Manager
(Pdb) p typ.type.fullname
'django.db.models.manager.Manager'
(Pdb) p fullnames.MANAGER_CLASSES
{'django.db.models.manager.BaseManager', 'django.db.models.manager.Manager'}
(Pdb) p typ.args
[]
```

**Comment by dfarley1** [comment]
I ran some tests on our code with a small fix seems to have fixed the problem:
```
-        return typ.type.fullname in fullnames.MANAGER_CLASSES and isinstance(typ.args[0], AnyType)
+        is_manager = typ.type.fullname in fullnames.MANAGER_CLASSES
+        is_AnyType = isinstance(typ.args[0], AnyType) if typ.args else False
+        return is_manager and is_AnyType

```

**Comment by sobolevn** [comment]
@dfarley1 would you please submit a test case for this and your fix?

**Comment by dfarley1** [comment]
Turns out I had other issues going on with our repo, this bug's invalid.
