### ISSUE TITLE
ValueError: Related model 'users.User' cannot be resolved

### ISSUE THREAD

**Issue by vkukushkin88** [typeddjango/django-stubs#403]
# Bug report

Crashing trying resolve related model.

## What's wrong

```
./apps/webapi/serializers/planes.py:145: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.770
Traceback (most recent call last):
  File "mypy/checkexpr.py", line 3749, in accept
  File "mypy/nodes.py", line 1544, in accept
  File "mypy/checkexpr.py", line 263, in visit_call_expr
  File "mypy/checkexpr.py", line 340, in visit_call_expr_inner
  File "mypy/checkexpr.py", line 817, in check_call_expr_with_callee_type
  File "mypy/checkexpr.py", line 903, in check_call
  File "mypy/checkexpr.py", line 876, in check_call
  File "mypy/checkexpr.py", line 984, in check_callable_call
  File "mypy/checkexpr.py", line 716, in apply_function_plugin
  File "/usr/local/lib/python3.8/site-packages/mypy_django_plugin/transformers/init_create.py", line 62, in redefine_and_typecheck_model_init
    return typecheck_model_method(ctx, django_context, model_cls, '__init__')
  File "/usr/local/lib/python3.8/site-packages/mypy_django_plugin/transformers/init_create.py", line 36, in typecheck_model_method
    expected_types = django_context.get_expected_types(typechecker_api, model_cls, method=method)
  File "/usr/local/lib/python3.8/site-packages/mypy_django_plugin/django/context.py", line 166, in get_expected_types
    field_set_type = self.get_field_set_type(api, field, method=method)
  File "/usr/local/lib/python3.8/site-packages/mypy_django_plugin/django/context.py", line 248, in get_field_set_type
    target_field = field.target_field
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related.py", line 878, in target_field
    return self.foreign_related_fields[0]
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related.py", line 632, in foreign_related_fields
    return tuple(rhs_field for lhs_field, rhs_field in self.related_fields if rhs_field)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related.py", line 619, in related_fields
    self._related_fields = self.resolve_related_fields()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related.py", line 604, in resolve_related_fields
    raise ValueError('Related model %r cannot be resolved' % self.remote_field.model)
ValueError: Related model 'apps-users.User' cannot be resolved
./apps/webapi/serializers/planes.py:144: : note: use --pdb to drop into pdb

```

Code which case error:
```
# file -> /apps/webapi/models/users.py
class AbstractCreatedByUpdatedByModel(serializers.ModelSerializer):
    """"""

    created_by = models.ForeignKey('apps-users.User',
                                   related_name='+',
                                   verbose_name=_('Created by'),
                                   blank=True,
                                   null=True,
                                   on_delete=models.SET_NULL)
    updated_by = models.ForeignKey('apps-users.User',
                                   related_name='+',
                                   verbose_name=_('Updated by'),
                                   blank=True,
                                   null=True,
                                   on_delete=models.SET_NULL)

    class Meta:
        """"""
        abstract = True


# It is actually is apps-users.User model
class User(AbstractUser, AbstractCreatedByUpdatedByModel):
    """User entity."""

    username = None  # type: ignore
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    email = models.EmailField(_('email address'), unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS: List[str] = []

    objects = UsersManager()

# file -> /apps/webapi/models/planes.py
class BaseConfigSection(AbstractCreatedByUpdatedByModel):
    """Base config section entity."""

    class Meta:
        """Base config section meta info."""

        verbose_name = _('Section')
        verbose_name_plural = _('Sections')
        unique_together = ('config', 'name')
        abstract = True


# file -> /apps/webapi/serializers/planes.py
class BaseSectionsConfigSerializer(serializers.ModelSerializer):
    """Base  sections config serializer."""

    sections_class: Type[BaseConfigSection]

    class Meta:
        """Serializer meta info."""

        fields = (
            'id',
            'sections',
        )

    def create(self, validated_data: Dict[str, Any]) -> CONFIG_CLS:
        """Create. """
        sections_data = validated_data.pop('sections')
        config = super().create(validated_data)
        self._create_related_sections(config=config,
                                      sections_data=sections_data)
        return config

    def _create_related_sections(self, config, sections_data):
        self.sections_class.objects.bulk_create(
            self.sections_class(config=config, **section)   # ERROR are here, LINE 144
            for section
            in sections_data)
```

I think that problem is that related model has ForeignKey like: `created_by = models.ForeignKey('users.User',....)` and it make dependency to itself.

## How is that should be

Should proper resolve dependencies and not crash. 
Regards.

## System information

- OS: 4.19.76-linuxkit GNU/Linux
- `python` version: 3.8.3
- `django` version: 2.2.10
- `mypy` version: 0.770
- `django-stubs` version: 1.5.0

**Comment by sobolevn** [comment]
I am pretty sure that the problem is that `apps-users` is not a valid app name.

**Comment by vkukushkin88** [comment]
> I am pretty sure that the problem is that `apps-users` is not a valid app name.

Code from my example is is not real code, it is just schema.
In real life it works pretty good more than 2 years. `apps-users` in real life has different name (I cannot provide real snapshot of code). I show you only general case.
It looks like that `django-stubs` cannot properly resolve referenced ForeignKey keys if it referenced to itself.

**Comment by bryanhelmig** [comment]
Same issue here!

**Comment by MAHANTH-wq** [comment]
same issue here

**Comment by sobolevn** [comment]
I would love to fix this issue, but I need a fully reproducable failure. Can someone please create a minimal repo with the failure?

**Comment by zume2020** [comment]
I had the same problem, fixed it just by ```manage.py migrate <app_name>```

with this model : 
```
class User(AbstractUser):
    date_of_birth = models.DateField()

```
I was getting  **ValueError: Related model 'api.user' cannot be resolved**

**Comment by ghost** [comment]
@zume2020 are you able to upload a full repo with that issue? i also can't reproduce this at all

**Comment by DedMaxTech** [comment]
same issue

**Comment by ghost** [comment]
@MaxGyverTech would you be willing to upload a failing repo so we can look at it?

**Comment by jordaneremieff** [comment]
I ran into the same (or very similar) issue for a model that uses a self-referential foreign-key. I was able to reproduce this from a minimal/fresh Django project using the following these steps:

1. `pip install django django-stubs mypy`

Resulting `pip freeze`:

```shell
Django==3.2.4
django-stubs==1.8.0
django-stubs-ext==0.2.0
mypy==0.902
mypy-extensions==0.4.3
pytz==2021.1
sqlparse==0.4.1
toml==0.10.2
typing-extensions==3.10.0.0
```

2. `django-admin startproject myproject && cd myproject && django-admin startapp myapp`

3. Include `myapp` to `INSTALLED_APPS` in `myproject/settings.py`

4. Create a model with a self-referential foreign-key:

```python
myapp/models.py
from django.db import models


class BaseEmployee(models.Model):

    manager = models.ForeignKey("self", on_delete=models.CASCADE)

    class Meta:
        abstract = True


class Employee(BaseEmployee):
    salary = models.TextField()

class Contractor(BaseEmployee):
    rate = models.TextField()
```
5. `./manage.py makemigrations && ./manage.py migrate`

6. Create a file containing the method that produces the error:

```python
from typing import Type

from .models import BaseEmployee


def make_new_employee(model_class: Type[BaseEmployee]) -> BaseEmployee:
    # ...
    return model_class()

```

7. Create `mypy.ini`:

```shell
[mypy]
plugins = 
    mypy_django_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = "myproject.settings"

```

8. Run `mypy myapp` to produce this error:

```shell
myapp/employees.py:9: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.812
Traceback (most recent call last):
  File "mypy/checkexpr.py", line 3898, in accept
  File "mypy/nodes.py", line 1555, in accept
  File "mypy/checkexpr.py", line 270, in visit_call_expr
  File "mypy/checkexpr.py", line 347, in visit_call_expr_inner
  File "mypy/checkexpr.py", line 852, in check_call_expr_with_callee_type
  File "mypy/checkexpr.py", line 942, in check_call
  File "mypy/checkexpr.py", line 911, in check_call
  File "mypy/checkexpr.py", line 1023, in check_callable_call
  File "mypy/checkexpr.py", line 723, in apply_function_plugin
  File "/Users/jordan/.pyenv/versions/3.8.8/lib/python3.8/site-packages/mypy_django_plugin/transformers/init_create.py", line 63, in redefine_and_typecheck_model_init
    return typecheck_model_method(ctx, django_context, model_cls, "__init__")
  File "/Users/jordan/.pyenv/versions/3.8.8/lib/python3.8/site-packages/mypy_django_plugin/transformers/init_create.py", line 38, in typecheck_model_method
    expected_types = django_context.get_expected_types(typechecker_api, model_cls, method=method)
  File "/Users/jordan/.pyenv/versions/3.8.8/lib/python3.8/site-packages/mypy_django_plugin/django/context.py", line 165, in get_expected_types
    field_set_type = self.get_field_set_type(api, field, method=method)
  File "/Users/jordan/.pyenv/versions/3.8.8/lib/python3.8/site-packages/mypy_django_plugin/django/context.py", line 244, in get_field_set_type
    target_field = field.target_field
  File "/Users/jordan/.pyenv/versions/3.8.8/lib/python3.8/site-packages/django/db/models/fields/related.py", line 897, in target_field
    return self.foreign_related_fields[0]
  File "/Users/jordan/.pyenv/versions/3.8.8/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/jordan/.pyenv/versions/3.8.8/lib/python3.8/site-packages/django/db/models/fields/related.py", line 644, in foreign_related_fields
    return tuple(rhs_field for lhs_field, rhs_field in self.related_fields if rhs_field)
  File "/Users/jordan/.pyenv/versions/3.8.8/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/jordan/.pyenv/versions/3.8.8/lib/python3.8/site-packages/django/db/models/fields/related.py", line 632, in related_fields
    return self.resolve_related_fields()
  File "/Users/jordan/.pyenv/versions/3.8.8/lib/python3.8/site-packages/django/db/models/fields/related.py", line 936, in resolve_related_fields
    related_fields = super().resolve_related_fields()
  File "/Users/jordan/.pyenv/versions/3.8.8/lib/python3.8/site-packages/django/db/models/fields/related.py", line 615, in resolve_related_fields
    raise ValueError('Related model %r cannot be resolved' % self.remote_field.model)
ValueError: Related model 'self' cannot be resolved
```

The example method is based on the example here: https://docs.python.org/3/library/typing.html#typing.Type.

Note: I don't personally require a resolution for this because the code raising the error is being deprecated/removed from the system that I'm working on - just providing these details in case it may assist someone else with this problem.

**Comment by empeje** [comment]
I have the same issue when I try to change the `AUTH_USER_MODEL`.  Moving the `User` model to entirely new app solve the issue in my case.

Initially I have `User` class inside my `ai_app` and I got the same issue. After I create an entirely new app inside `users`:  `python manage.py startapp users` and create the class inside the new app it solve my issue.

**Before:**

```python
AUTH_USER_MODEL = 'ai_app.User'
```

Doesn't work. 👎 

**After:**

```python
AUTH_USER_MODEL = 'users.User'
```
Work 👍

**Comment by abmaelbandeira** [comment]
In my case, the application was running normally, but I was having this same error when running pytest, I solved the problem by removing `AUTH_USER_MODEL="app_name.User" `from my settings_for_tests.py.
I ran pytest as follows:

`pytest app_name --ds=app_name.settings_for_tests`
