### ISSUE TITLE
ModuleNotFoundError - can't find app

### ISSUE THREAD

**Issue by ilyachch** [typeddjango/django-stubs#456]
# Bug report

## What's wrong

My project structure is
```
├── Makefile
├── README.md
├── backend
│   ├── backend
│   │   ├── __init__.py
│   │   ├── asgi.py
│   │   ├── settings.py
│   │   ├── urls.py
│   │   └── wsgi.py
│   ├── base
│   │   ├── __init__.py
│   │   ├── admin.py
│   │   ├── apps.py
│   │   ├── migrations
│   │   │   ├── 0001_initial.py
│   │   │   └── __init__.py
│   │   ├── models.py
│   │   └── views.py
│   └── manage.py
├── mypy.ini
├── poetry.lock
└── pyproject.toml
```

My `mypy.ini` file is:
```
[mypy]
plugins = mypy_django_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = "backend.backend.settings"

[mypy-*.migrations.*]
ignore_errors = True
```

I'm trying to run `poetry run mypy backend` but error appers:
```
Error constructing plugin instance of NewSemanalDjangoPlugin

Traceback (most recent call last):
  File ".../Library/Caches/pypoetry/virtualenvs/backend--9yB--ih-py3.8/bin/mypy", line 10, in <module>
    sys.exit(console_entry())
  File ".../Library/Caches/pypoetry/virtualenvs/backend--9yB--ih-py3.8/lib/python3.8/site-packages/mypy/__main__.py", line 8, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 89, in main
  File "mypy/build.py", line 180, in build
  File "mypy/build.py", line 227, in _build
  File "mypy/build.py", line 465, in load_plugins
  File "mypy/build.py", line 443, in load_plugins_from_config
  File ".../Library/Caches/pypoetry/virtualenvs/backend--9yB--ih-py3.8/lib/python3.8/site-packages/mypy_django_plugin/main.py", line 80, in __init__
    self.django_context = DjangoContext(django_settings_module)
  File ".../Library/Caches/pypoetry/virtualenvs/backend--9yB--ih-py3.8/lib/python3.8/site-packages/mypy_django_plugin/django/context.py", line 88, in __init__
    apps, settings = initialize_django(self.django_settings_module)
  File ".../Library/Caches/pypoetry/virtualenvs/backend--9yB--ih-py3.8/lib/python3.8/site-packages/mypy_django_plugin/django/context.py", line 72, in initialize_django
    apps.populate(settings.INSTALLED_APPS)
  File ".../Library/Caches/pypoetry/virtualenvs/backend--9yB--ih-py3.8/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File ".../Library/Caches/pypoetry/virtualenvs/backend--9yB--ih-py3.8/lib/python3.8/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File ".../.pyenv/versions/3.8.2/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'base'
```

The app `base` is in `INSTALLED_APPS`:
```
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'base',
]
```

If i make a copy of `mypy.ini` inside of backend folder, near `manage.py` and run `poetry run mypy .` from this folder, it works. 

## How is that should be

I think it should be run normally

## System information

- OS: MacOS X 10.14.6
- `python` version: 3.8.2
- `django` version: 3.1.1
- `mypy` version: 0.770
- `django-stubs` version: 1.5.0

**Comment by sobolevn** [comment]
Yes, `mypy.ini` should be near `manage.py` 👍 

Going to close this, because there's nothing to fix!
