### ISSUE TITLE
Incompatible with celery 

### ISSUE THREAD

**Issue by danjac** [typeddjango/django-stubs#613]
# Bug report

Unable to run mypy with django-stubs, even with` ignore_missing_imports=true`.

Celery is set up in the root `__init__.py` file:

```
from myapp.config.celery_app import app as celery_app

__all__ = ["celery_app"]
```

```
Error constructing plugin instance of NewSemanalDjangoPlugin

Traceback (most recent call last):
  File "/home/danjac/.cache/pre-commit/repofnhxp939/py_env-python3.9/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/danjac/.cache/pre-commit/repofnhxp939/py_env-python3.9/lib64/python3.9/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 90, in main
  File "mypy/build.py", line 179, in build
  File "mypy/build.py", line 228, in _build
  File "mypy/build.py", line 472, in load_plugins
  File "mypy/build.py", line 450, in load_plugins_from_config
  File "/home/danjac/.cache/pre-commit/repofnhxp939/py_env-python3.9/lib/python3.9/site-packages/mypy_django_plugin/main.py", line 104, in __init__
    self.django_context = DjangoContext(django_settings_module)
  File "/home/danjac/.cache/pre-commit/repofnhxp939/py_env-python3.9/lib/python3.9/site-packages/mypy_django_plugin/django/context.py", line 88, in __init__
    apps, settings = initialize_django(self.django_settings_module)
  File "/home/danjac/.cache/pre-commit/repofnhxp939/py_env-python3.9/lib/python3.9/site-packages/mypy_django_plugin/django/context.py", line 70, in initialize_django
    settings._setup()
  File "/home/danjac/.cache/pre-commit/repofnhxp939/py_env-python3.9/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/danjac/.cache/pre-commit/repofnhxp939/py_env-python3.9/lib/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/project-path/my-app/__init__.py", line 2, in <module>
    from myapp.config.celery_app import app as celery_app
  File "/project-path/myapp/config/celery_app.py", line 3, in <module>
    from celery import Celery
ModuleNotFoundError: No module named 'celery'
```

As the app itself is running in a Docker container and mypy is running in a pre-commit hook, I have set `ignore_missing_imports=true`. However it appears the django-stubs plugin ignores this setting.

The issue may not be related as such to celery: commenting out the celery imports in the root `__init__.py` causes `ModuleNotFoundErrors` with other missing imports.

setup.cfg:

```

[mypy]
python_version = 3.9
allow_subclassing_any = true
check_untyped_defs = true
ignore_missing_imports = true
follow_imports = silent
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true

plugins = mypy_django_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = myapp.config.settings.test

[mypy-*.tests.*]
ignore_errors = true

[mypy-*.migrations.*]
# Django migrations should not produce any errors:
ignore_errors = true
```

## How is that should be

Should be able to run mypy checks without crashing.

## System information

- OS:
- `python` version: 3.9 
- `django` version: 3.2
- `mypy` version: 0.812
- `django-stubs` version: 1.8.0

**Comment by sobolevn** [comment]
Do you have `celery` installed? Because we actually run `django.setup()` to build our model types. If you don't have `celery` installed - it would fail.

**Comment by danjac** [comment]
So this looks like a fundamental problem with django-stubs. My Django app runs inside a Docker container, and pre-commit is running outside that container (this is probably going to be an issue with anything else running outside the container, e.g. VSCode).

So the only way I can get this to work - if django.setup() is being run as part of the type checking - is to run mypy inside the container. That works,  but it's useless with any external tooling that runs outside the container.

Am I correct? Would that not negate much of the usefulness of typing as a tooling integration?

**Comment by sobolevn** [comment]
> So this looks like a fundamental problem with django-stubs

Yes, it is. But on the other hand, we made this decision to simplify our plugin and make it more correct.

> So the only way I can get this to work - if django.setup() is being run as part of the type checking - is to run mypy inside the container.

Yes, this is how it should be done. Moreover, `mypy` loves to have all the dependencies during type checking. As far as I know, it is considered to be the best practice.

I am going to close this, because it is not a bug. We can continue the discussion here if you need any help from our side! 👍

**Comment by danjac** [comment]
Sure, I understand the reasons. Unfortunately it does limit usage of full type checking in certain toolchains but there's a tradeoff either way.

Thanks for working on this!
