### ISSUE TITLE
Typing for Raw Django Class Model does not work

### ISSUE THREAD

**Issue by DabeLong** [typeddjango/django-stubs#655]
# Bug report
Normally, a model M should be of type "M"
For example, M.objects.create(<...arguments>) will be of type M.
However, if using M(...arguments), should also be of type M.

## What's wrong
Running typecheck for M(...arguments) causes an internal error.

## How is that should be
M(...arguments) should evaluate to type M

**Comment by DabeLong** [comment]
i.e.
I have a Django model Car.
Typechecking works if I do car = Car.objects.create(make='"BMW')

But it doesn't work if I do car = Car(make='"BMW')

There are times where I may need to do the 2nd way, in cases I would like to use bulk_create for example.
cars = Car.objects.bulk_create([car1, car2, ...])

Here is a sample stack trace:
test_models.py:12: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.rtfd.io/en/latest/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.812
test_models.py:12: : note: use --pdb to drop into pdb
Traceback (most recent call last):
FAIL: //typecheck
INFO: From Testing typecheck:
  File "mypy/checkexpr.py", line 3898, in accept
  File "mypy/nodes.py", line 1555, in accept
  File "mypy/checkexpr.py", line 270, in visit_call_expr
  File "mypy/checkexpr.py", line 347, in visit_call_expr_inner
  File "mypy/checkexpr.py", line 852, in check_call_expr_with_callee_type
  File "mypy/checkexpr.py", line 911, in check_call
  File "mypy/checkexpr.py", line 1023, in check_callable_call
  File "mypy/checkexpr.py", line 723, in apply_function_plugin
  File "mypy_runner.sh.runfiles/bamboo_pip_deps/pypi__django_stubs/mypy_django_plugin/transformers/init_create.py", line 62, in redefine_and_typecheck_model_init
    return typecheck_model_method(ctx, django_context, model_cls, '__init__')
  File "mypy_runner.sh.runfiles/bamboo_pip_deps/pypi__django_stubs/mypy_django_plugin/transformers/init_create.py", line 36, in typecheck_model_method
    expected_types = django_context.get_expected_types(typechecker_api, model_cls, method=method)
  File "/mypy_runner.sh.runfiles/bamboo_pip_deps/pypi__django_stubs/mypy_django_plugin/django/context.py", line 154, in get_expected_types
    from django.contrib.contenttypes.fields import GenericForeignKey
  File "/mypy_runner.sh.runfiles/bamboo_pip_deps/pypi__django/django/contrib/contenttypes/fields.py", line 6, in <module>
    from django.contrib.contenttypes.models import ContentType
  File "mypy_runner.sh.runfiles/bamboo_pip_deps/pypi__django/django/contrib/contenttypes/models.py", line 133, in <module>
    class ContentType(models.Model):
  File "mypy_runner.sh.runfiles/bamboo_pip_deps/pypi__django/django/db/models/base.py", line 113, in __new__
    raise RuntimeError(
RuntimeError: Model class django.contrib.contenttypes.models.ContentType doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
From mypy_runner.sh.runfiles/rh/bamboo/mypy_runner.sh:

**Comment by DabeLong** [comment]
Needed to update to 1.8 version
