### ISSUE TITLE
mypy_django_plugin cannot parse pyproject.toml containing multiline string

### ISSUE THREAD

**Issue by jacobjove** [typeddjango/django-stubs#691]
# Bug report

## What's wrong

I can't run mypy with mypy_django_plugin based on a pyproject.toml config; it fails with parsing errors due to encountering the following Black config containing a multiline string:

```
[tool.black]
# https://black.readthedocs.io/en/stable/
# https://github.com/psf/black/blob/main/pyproject.toml
line-length = 94
skip-string-normalization = true
include = '\.py$'
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.cache
    | \.venv
  )/
)
'''
```

Here is the mypy config in the same file:

```
[tool.mypy]
python_version = 3.9
cache_dir = ".cache/mypy"
# https://mypy.readthedocs.io/en/stable/config_file.html#confval-check_untyped_defs
check_untyped_defs = true
# https://mypy.readthedocs.io/en/stable/config_file.html#confval-disallow_untyped_calls
disallow_untyped_calls = false
# https://mypy.readthedocs.io/en/stable/config_file.html#confval-ignore_errors
ignore_errors = false
# https://mypy.readthedocs.io/en/stable/config_file.html#confval-no_implicit_optional
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_unused_ignores = false
warn_redundant_casts = true
warn_unused_configs = true
# https://mypy.readthedocs.io/en/stable/config_file.html#confval-warn_unreachable
warn_unreachable = true
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]

[[tool.mypy.overrides]]
module = ["*.migrations.*", "__init__"]
ignore_errors = true

[tool.django-stubs]
django_settings_module = "core.settings"
ignore_missing_model_attributes = true
```

## How it should be

Mypy with mypy_django_plugin should run successfully regardless of the presence of multiline strings in pyproject.toml.

## System information

- OS:
- `python` version: 3.9
- `django` version: 3.1
- `mypy` version: 0.910
- `django-stubs` version: 1.8.0

**Comment by sobolevn** [comment]
Here's the code that does the `toml` parsing: https://github.com/typeddjango/django-stubs/blob/master/mypy_django_plugin/main.py#L105-L118

Can you please fix it? 🙂

**Comment by jacobjove** [comment]
Hmmm. Looks like the code in the master branch is different from what I have on my computer (v 1.8.0)...

The code running on my machine looks like this:
```
def extract_django_settings_module(config_file_path: Optional[str]) -> str:
    def exit(error_type: int) -> NoReturn:
        """Using mypy's argument parser, raise `SystemExit` to fail hard if validation fails.

        Considering that the plugin's startup duration is around double as long as mypy's, this aims to
        import and construct objects only when that's required - which happens once and terminates the
        run. Considering that most of the runs are successful, there's no need for this to linger in the
        global scope.
        """
        from mypy.main import CapturableArgumentParser

        usage = """(config)
        ...
        [mypy.plugins.django_stubs]
            django_settings_module: str (required)
        ...
        """.replace(
            "\n" + 8 * " ", "\n"
        )
        handler = CapturableArgumentParser(prog="(django-stubs) mypy", usage=usage)
        messages = {
            1: "mypy config file is not specified or found",
            2: "no section [mypy.plugins.django-stubs]",
            3: "the setting is not provided",
        }
        handler.error("'django_settings_module' is not set: " + messages[error_type])

    parser = configparser.ConfigParser()
    try:
        with open(cast(str, config_file_path)) as handle:
            parser.read_file(handle, source=config_file_path)
    except (IsADirectoryError, OSError):
        exit(1)

    section = "mypy.plugins.django-stubs"
    if not parser.has_section(section):
        exit(2)
    settings = parser.get(section, "django_settings_module", fallback=None) or exit(3)
    return cast(str, settings).strip("'\"")
```
So I guess the django-stubs code running on my computer is just missing the toml processing logic altogether. Should it be?

Here's the django-stubs entry in my poetry.lock:
```
[[package]]
name = "django-stubs"
version = "1.8.0"
description = "Mypy stubs for Django"
category = "dev"
optional = false
python-versions = ">=3.6"
```

**Comment by sobolevn** [comment]
Nope, `1.8` does not support `toml`, sorry, I've missed that! Can you please verify that `master` works for you in this specific case? 🙂

**Comment by feslima** [comment]
Hi guys, I have the same problem here with this addition in my `toml` file:

```shell
[[tool.mypy.overrides]]
module = "*.migrations.*"
ignore_errors = true

[[tool.mypy.overrides]]
module = ["psycopg2.*", "celery.*", "super_inlines.*", "imagekit.*", "debug_toolbar.*"]
ignore_missing_imports = true
```

The plugin does not accept two override sections. This is the traceback of the exception thrown:

```
Error constructing plugin instance of NewSemanalDjangoPlugin

Traceback (most recent call last):
  File "/home/felipe/project/.venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/felipe/project/.venv/lib/python3.8/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 87, in main
  File "mypy/main.py", line 165, in run_build
  File "mypy/build.py", line 179, in build
  File "mypy/build.py", line 229, in _build
  File "mypy/build.py", line 475, in load_plugins
  File "mypy/build.py", line 453, in load_plugins_from_config
  File "/home/felipe/project/.venv/lib/python3.8/site-packages/mypy_django_plugin/main.py", line 99, in __init__
    django_settings_module = extract_django_settings_module(options.config_file)
  File "/home/felipe/project/.venv/lib/python3.8/site-packages/mypy_django_plugin/main.py", line 85, in extract_django_settings_module
    parser.read_file(handle, source=config_file_path)
  File "/usr/lib/python3.8/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/lib/python3.8/configparser.py", line 1067, in _read
    raise DuplicateSectionError(sectname, fpname,
configparser.DuplicateSectionError: While reading from 'pyproject.toml' [line 72]: section '[tool.mypy.overrides' already exists
```

Should I open another issue about this or do I keep it here?

Thanks in advance.

**Comment by sobolevn** [comment]
I will close this, because this is just a version mismatch issue.
