### ISSUE TITLE
Mypy fatal error with querysets.values

### ISSUE THREAD

**Issue by PIG208** [typeddjango/django-stubs#693]
# Bug report

## What's wrong

```Python traceback
Traceback (most recent call last):
  File "mypy/checkexpr.py", line 3911, in accept
  File "mypy/nodes.py", line 1558, in accept
  File "mypy/checkexpr.py", line 271, in visit_call_expr
  File "mypy/checkexpr.py", line 353, in visit_call_expr_inner
  File "mypy/checkexpr.py", line 858, in check_call_expr_with_callee_type
  File "mypy/checkexpr.py", line 917, in check_call
  File "mypy/checkexpr.py", line 1029, in check_callable_call
  File "mypy/checkexpr.py", line 738, in apply_function_plugin
  File "/srv/zulip-venv-cache/fa0d660295d87196401d628cfb53dc3541486410/zulip-py3-venv/lib/python3.8/site-packages/mypy_django_plugin/transformers/querysets.py", line 273, in extract_proper_type_queryset_values
    assert isinstance(default_return_type, Instance)
AssertionError:
zerver/models.py:1048: : note: use --pdb to drop into pdb
```
```Python console
(Pdb) default_return_type
Any
(Pdb) ctx
MethodContext(type=django.db.models.manager.RelatedManager[zerver.models.RealmDomain], arg_types=[[Literal['domain']?, Literal['allow_subdomains']?], []], arg_kinds=[[0, 0], []], callee_arg_names=['fields', 'expressions'], arg_names=[[None, None], []], default_return_type=Any, args=[[<mypy.nodes.StrExpr object at 0x7f2c59b19720>, <mypy.nodes.StrExpr object at 0x7f2c59b19770>], []], context=<mypy.nodes.CallExpr object at 0x7f2c59b14970>, api=<mypy.checker.TypeChecker object at 0x7f2c53a6e160>
```

This is the line of code that mypy fails to check, where `Realm` is a model:
```python
def get_realm_domains(realm: Realm) -> List[Dict[str, str]]:
    return list(realm.realmdomain_set.values("domain", "allow_subdomains"))  # <<<
```

Similarly, this line of code leads to exactly the same error:
```python
stream = Stream.objects.values("name").get(id=recipient_type_id)
```

## How is that should be

No fatal errors should occur. This is likely an error introduced in cfd69c0acc4bb3c282cab4a411b014afe280d359.

## System information

- OS: Ubuntu 18.04/WSL Ubuntu 20.04
- `python` version: 3.8.5
- `django` version: 3.2.5
- `mypy` version: 0.910
- `django-stubs` version: dev (till 8674c48c596b7e3eee8f7d51467e98c7f66fe2f3)
- `django-stubs-ext` version: dev (till 8674c48c596b7e3eee8f7d51467e98c7f66fe2f3)

**Comment by PIG208** [comment]
After some investigation, I found that `py.typed` is not included when installing the dev version of `django_stubs_ext`. It's an error caused by incorrect `setup.py`. Working on a fix for this.
