### ISSUE TITLE
TypeError: basic_new_typeinfo() missing required argument 'line' (pos 3)

### ISSUE THREAD

**Issue by christianbundy** [typeddjango/django-stubs#699]
# Bug report

## What's wrong

```
Traceback (most recent call last):
  File "mypy/semanal.py", line 4872, in accept
  File "mypy/nodes.py", line 1073, in accept
  File "mypy/semanal.py", line 2023, in visit_assignment_stmt
  File "mypy/semanal.py", line 2278, in apply_dynamic_class_hook
  File "/.venv/lib/python3.9/site-packages/mypy_django_plugin/transformers/managers.py", line 22, in create_new_manager_class_from_from_queryset_method
    new_manager_info = semanal_api.basic_new_typeinfo(
TypeError: basic_new_typeinfo() missing required argument 'line' (pos 3)
```

## System information

- OS:
- `python` version: 3.9.6
- `django` version: 3.1
- `mypy` version: 0.910
- `django-stubs` version: 1.8.0

**Comment by sobolevn** [comment]
Does this happen with `mypy==0.900`?
Or with `mypy==0.910` and `master` version?

**Comment by sobolevn** [comment]
Yes, `master` and `mypy==0.910` works!

**Comment by christianbundy** [comment]
Woah, thank you!
