### ISSUE TITLE
django settings not parsed from pyproject.toml

### ISSUE THREAD

**Issue by dimbleby** [typeddjango/django-stubs#888]
# Bug report

## What's wrong

```toml
[tool.mypy]
strict = true
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]

[tool.django-stubs]
django_settings_module = "treasure.settings"
```

```
Error constructing plugin instance of NewSemanalDRFPlugin

Traceback (most recent call last):
  File "/home/dch/.virtualenvs/treasure/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/dch/.virtualenvs/treasure/lib/python3.8/site-packages/mypy/__main__.py", line 12, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 96, in main
  File "mypy/main.py", line 173, in run_build
  File "mypy/build.py", line 180, in build
  File "mypy/build.py", line 231, in _build
  File "mypy/build.py", line 478, in load_plugins
  File "mypy/build.py", line 456, in load_plugins_from_config
  File "/home/dch/.virtualenvs/treasure/lib/python3.8/site-packages/mypy_drf_plugin/main.py", line 25, in __init__
    django_settings_module = mypy_django_main.extract_django_settings_module(options.config_file)
AttributeError: module 'mypy_django_plugin.main' has no attribute 'extract_django_settings_module'
```
## How is that should be

Should Just Work, per README.

Have verified that going back to 1.9.0 the error does not happen.

## System information

- OS:
- `python` version: 3.8
- `django` version: 4.0.3
- `mypy` version: 0.942.0
- `django-stubs` version: 1.10.0
- `django-stubs-ext` version: n/a

**Comment by dimbleby** [comment]
Ah, I think I see: you've released an update to the main plugin that refactors the config reading; but the rest-framework plugin continues to rely on the old code.

**Comment by dimbleby** [comment]
And in fact now that I realise that I see that we already have https://github.com/typeddjango/djangorestframework-stubs/issues/202
