### ISSUE TITLE
`mypy_django_plugin` regression introduced between 1.9.0 and 1.10.0

### ISSUE THREAD

**Issue by tfranzel** [typeddjango/django-stubs#890]
# Bug report

So when GHA updated deps to the new version our build broke. This new version throws an attribute error that was not happening before. The recommended setup from the README seems unchanged so its unclear whether some changes are required on our side.

`django-stubs-1.9.0` -> ok
`django-stubs-1.10.0` -> broken

`tox.ini` excerpt: 
```
[mypy]
python_version = 3.9
plugins = mypy_django_plugin.main,mypy_drf_plugin.main
```

traceback:
```
# mypy --config-file tox.ini drf_spectacular tests        
Error constructing plugin instance of NewSemanalDRFPlugin

Traceback (most recent call last):
  File ".../drf-spectacular/venv/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File ".../drf-spectacular/venv/lib/python3.9/site-packages/mypy/__main__.py", line 12, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 96, in main
  File "mypy/main.py", line 173, in run_build
  File "mypy/build.py", line 180, in build
  File "mypy/build.py", line 231, in _build
  File "mypy/build.py", line 478, in load_plugins
  File "mypy/build.py", line 456, in load_plugins_from_config
  File ".../venv/lib/python3.9/site-packages/mypy_drf_plugin/main.py", line 25, in __init__
    django_settings_module = mypy_django_main.extract_django_settings_module(options.config_file)
AttributeError: module 'mypy_django_plugin.main' has no attribute 'extract_django_settings_module'
```

for reference a failing action: https://github.com/tfranzel/drf-spectacular/runs/5710587552?check_suite_focus=true#step:6:30

## System information

- `python` version: 3.9
- `django` version: 4.0.3
- `mypy` version: 0.942
- `django-stubs` version: SEE ABOVE
- `django-stubs-ext` version: 0.3.1

**Comment by sobolevn** [comment]
See https://github.com/typeddjango/djangorestframework-stubs/pull/203
