### ISSUE TITLE
module 'mypy_django_plugin.main' has no attribute 'extract_django_settings_module'

### ISSUE THREAD

**Issue by ethteck** [typeddjango/django-stubs#898]
# Bug report

## What's wrong

In trying to update from django-stubs 1.9.0 to 1.10.0 in my project, running `poetry run mypy` causes the following issue:

```
ethteck@SNAILSHELL:~/repos/decomp.me/backend$ poetry run mypy
Error constructing plugin instance of NewSemanalDRFPlugin

Traceback (most recent call last):
  File "/home/ethteck/.cache/pypoetry/virtualenvs/backend-Mj-ssBpK-py3.10/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/ethteck/.cache/pypoetry/virtualenvs/backend-Mj-ssBpK-py3.10/lib/python3.10/site-packages/mypy/__main__.py", line 12, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 96, in main
  File "mypy/main.py", line 173, in run_build
  File "mypy/build.py", line 180, in build
  File "mypy/build.py", line 231, in _build
  File "mypy/build.py", line 478, in load_plugins
  File "mypy/build.py", line 456, in load_plugins_from_config
  File "/home/ethteck/.cache/pypoetry/virtualenvs/backend-Mj-ssBpK-py3.10/lib/python3.10/site-packages/mypy_drf_plugin/main.py", line 25, in __init__
    django_settings_module = mypy_django_main.extract_django_settings_module(options.config_file)
AttributeError: module 'mypy_django_plugin.main' has no attribute 'extract_django_settings_module'
```

## How is that should be
No error

## System information

- OS: Ubuntu 21.10 (Windows 11 WSL)
- `python` version: 3.10.0
- `django` version: 4.0.3
- `mypy` version: 0.931
- `django-stubs` version: 1.9.0 -> 1.10.0
- `django-stubs-ext` version: 0.4.0

**Comment by sobolevn** [comment]
See https://github.com/typeddjango/djangorestframework-stubs/issues/202
